---
- name: Install build-essential for building dependencies
  apt:
    name: build-essential
    state: present

- name: Install python3-venv
  apt:
    name: python3-venv
    state: present

- name: Create Python virtual environment
  shell: python3 -m venv /home/jenkins/venv

- name: Upgrade pip, setuptools, and wheel
  pip:
    virtualenv: /home/jenkins/venv
    name:
      - pip
      - setuptools
      - wheel
    extra_args: --upgrade

- name: Install cython
  pip:
    virtualenv: /home/jenkins/venv
    name: cython
    state: present

- name: Install pip inside virtualenv
  pip:
    virtualenv: /home/jenkins/venv
    name:
      - docker
      - docker-compose

- name: Run container
  docker_container:
    name: wartest
    image: "{{ image }}"
    ports:
      - "8081:8080"
    state: started
