---
- name: Install system dependencies for Python and building
  apt:
    name:
      - build-essential
      - python3-venv
      - python3-dev
      - libyaml-dev
    state: present
    update_cache: yes

- name: Create Python virtual environment
  shell: python3 -m venv /home/jenkins/venv
  args:
    creates: /home/jenkins/venv

- name: Upgrade pip, setuptools, and wheel in the virtual environment
  shell: >
    /home/jenkins/venv/bin/pip3 install --upgrade pip setuptools wheel
  args:
    creates: /home/jenkins/venv/bin/pip3

- name: Install cython in the virtual environment
  shell: >
    /home/jenkins/venv/bin/pip3 install cython
  args:
    creates: /home/jenkins/venv/bin/cython

- name: Install required Python libraries in the virtual environment
  shell: >
    /home/jenkins/venv/bin/pip3 install PyYAML docker docker-compose
  args:
    creates: /home/jenkins/venv/bin/docker-compose

- name: Ensure the wartest container is running
  docker_container:
    name: wartest
    image: "{{ image }}"
    ports:
      - "8081:8080"
    state: started

- name: Debug container status
  shell: docker ps | grep wartest
