---
- name: Install system dependencies for Python and building
  apt:
    name:
      - build-essential
      - python3.10
      - python3.10-venv
      - python3.10-dev
      - libyaml-dev
      - libffi-dev
      - libssl-dev
      - gcc
    state: present
    update_cache: yes

- name: Ensure Python 3.10 is the default Python3
  shell: |
    update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.10 1
    update-alternatives --set python3 /usr/bin/python3.10

- name: Create Python virtual environment
  shell: python3 -m venv /home/jenkins/venv
  args:
    creates: /home/jenkins/venv

- name: Upgrade pip, setuptools, and wheel in the virtual environment
  shell: |
    /home/jenkins/venv/bin/pip3 install --upgrade pip setuptools wheel
  args:
    creates: /home/jenkins/venv/bin/pip3

- name: Install specific version of PyYAML
  shell: |
    /home/jenkins/venv/bin/pip3 install PyYAML==5.4.1 --no-build-isolation --use-deprecated=legacy-resolver
  args:
    creates: /home/jenkins/venv/lib/python3.10/site-packages/yaml

- name: Install cython in the virtual environment
  shell: |
    /home/jenkins/venv/bin/pip3 install cython
  args:
    creates: /home/jenkins/venv/bin/cython

- name: Install required Python libraries in the virtual environment
  shell: |
    /home/jenkins/venv/bin/pip3 install docker==6.0.1 docker-compose==1.29.2 --no-build-isolation --use-deprecated=legacy-resolver
  args:
    creates: /home/jenkins/venv/bin/docker-compose

- name: Ensure the wartest container is running
  docker_container:
    name: wartest
    image: "{{ image }}"
    ports:
      - "8081:8080"
    state: started

- name
