---
- name: Install system dependencies for Python and building
  apt:
    name:
      - build-essential
      - python3.10
      - python3.10-venv
      - python3.10-dev
      - libyaml-dev
      - libffi-dev
      - libssl-dev
      - gcc
    state: present
    update_cache: yes

- name: Ensure Python 3.10 is the default Python3
  shell: |
    update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.10 1
    update-alternatives --set python3 /usr/bin/python3.10
  args:
    warn: false

- name: Create Python virtual environment
  ansible.builtin.command: python3 -m venv /home/jenkins/venv
  args:
    creates: /home/jenkins/venv

- name: Upgrade pip, setuptools, and wheel in the virtual environment
  ansible.builtin.shell: |
    /home/jenkins/venv/bin/pip3 install --upgrade pip setuptools wheel
  args:
    executable: /bin/bash

- name: Install specific version of PyYAML
  ansible.builtin.shell: |
    /home/jenkins/venv/bin/pip3 install PyYAML==5.4.1 --no-build-isolation --use-deprecated=legacy-resolver
  args:
    executable: /bin/bash
  register: install_pyyaml
  failed_when: "'error' in install_pyyaml.stderr or install_pyyaml.rc != 0"

- name: Install Cython in the virtual environment
  ansible.builtin.shell: |
    /home/jenkins/venv/bin/pip3 install cython
  args:
    executable: /bin/bash

- name: Install required Python libraries in the virtual environment
  ansible.builtin.shell: |
    /home/jenkins/venv/bin/pip3 install docker==6.0.1 docker-compose==1.29.2 --no-build-isolation --use-deprecated=legacy-resolver
  args:
    executable: /bin/bash
  register: install_docker
  failed_when: "'error' in install_docker.stderr or install_docker.rc != 0"

- name: Ensure the wartest container is running
  community.docker.docker_container:
    name: wartest
    image: "{{ image }}"
    ports:
      - "8081:8080"
    state: started

- name: Check if the wartest container is running
  community.docker.docker_container_info:
    name: wartest
  register: container_info

- name: Ensure the container is healthy
  ansible.builtin.debug:
    msg: "Container wartest is running and healthy. Info: {{ container_info.container }}"
    when: container_info.container.State.Status == "running"
